"""Write DESIGN-SYSTEM.md and DESIGN-SYSTEM.html: the project's design system, readable without opening tokens.json."""
from __future__ import annotations

import json
import re
from html.parser import HTMLParser
from pathlib import Path
from types import SimpleNamespace

from build_tokens import collect, reference, scalar
from check_system import ROOT_PX, fmt, html_pages, project_breakpoints
from colors import to_hex, token_rgba
from design_page import PAGE_FILENAME, render_page
from naming import namespace_for
from report import plural
from themes import css_rules, project_themes, theme_rules

ROOT = Path(__file__).resolve().parents[1]
BASELINE = ROOT / "starter" / "tokens" / "tokens.json"
FILENAME = "DESIGN-SYSTEM.md"
HEADER = ("# Design system\n\n"
          "Generated by Portably from `tokens/tokens.json`, `portably.config.json` and the project's HTML and CSS. "
          "Don't edit this file by hand: change those, then run `python portably.py check`. "
          "`DESIGN-SYSTEM.html` shows the same system drawn with the project's own tokens.\n")
# The page anatomy is the same in every project, so the component map leaves it out.
ANATOMY = {"section", "wrapper", "section-header", "eyebrow", "app-shell", "panel"}


def config_of(project):
    path = project / "portably.config.json"
    return json.loads(path.read_text(encoding="utf-8")) if path.is_file() else {}


def px_text(value):
    if value["unit"] == "em":
        return f"{fmt(value['value'])}em"
    px = value["value"] * (ROOT_PX if value["unit"] == "rem" else 1)
    return f"{fmt(px)}px"


class Describer:
    def __init__(self, tokens):
        self.tokens = tokens

    def resolved(self, path, seen=()):
        token = self.tokens[path]
        target = reference(token["$value"])
        if target and target in self.tokens and target not in seen:
            return self.resolved(target, seen + (path,))
        return token

    def value(self, path):
        """A short human value: #2563EB, 16px, 600, 1.5…"""
        token = self.resolved(path)
        kind, value = token["$type"], token["$value"]
        if kind == "color":
            rgb, alpha = token_rgba(value)
            text = to_hex(rgb) + (f" at {fmt(round(alpha * 100, 1))}%" if alpha < 1 else "")
            if isinstance(value, str) and not value.strip().startswith("#"):
                text += f" (`{value.strip()}`)"
            return text
        if kind == "dimension":
            return px_text(value)
        if kind == "typography":
            parts = []
            for field in ("fontSize", "fontWeight", "lineHeight"):
                item = value[field]
                target = reference(item)
                parts.append(f"`{target}` ({self.value(target)})" if target else str(item))
            return " · ".join(parts)
        try:
            return scalar(value, kind)
        except (ValueError, KeyError, TypeError):
            return str(value)

    def shown(self, path):
        target = reference(self.tokens[path]["$value"])
        if target:
            return f"`{target}` ({self.value(path)})"
        return self.value(path)

    def note(self, path):
        return self.tokens[path].get("$description", "")


def table(head, rows):
    if not rows:
        return "_None._\n"
    keep = [i for i in range(len(head)) if i == 0 or any(str(row[i]).strip() for row in rows)]
    head = [head[i] for i in keep]
    rows = [[row[i] for i in keep] for row in rows]
    lines = ["| " + " | ".join(head) + " |", "|" + "|".join(" --- " for _ in head) + "|"]
    lines += ["| " + " | ".join(str(cell).replace("|", "\\|") for cell in row) + " |" for row in rows]
    return "\n".join(lines) + "\n"


def notes(value):
    """A config entry as a list of sentences; a single sentence is a list of one."""
    if isinstance(value, str):
        return [value] if value.strip() else []
    return [item for item in value if isinstance(item, str)] if isinstance(value, list) else []


def bullets(items):
    return "\n".join(f"- {item}" for item in items) + "\n" if items else "_None._\n"


class PageClasses(HTMLParser):
    def __init__(self):
        super().__init__()
        self.classes = set()
        self.title = ""
        self.in_title = False

    def handle_starttag(self, tag, attrs):
        self.classes.update((dict(attrs).get("class") or "").split())
        self.in_title = tag == "title"

    def handle_endtag(self, tag):
        self.in_title = False

    def handle_data(self, data):
        if self.in_title:
            self.title += data


def css_blocks(text, namespace):
    """The project's own BEM blocks a stylesheet styles: `.pricing-card__price` → `pricing-card`."""
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    blocks = set()
    for header in re.findall(r"([^{}]+)\{", text):
        if header.strip().startswith("@"):
            continue
        for name in re.findall(r"\.(-?[A-Za-z_][\w-]*)", header):
            block = name.split("__")[0].split("--")[0]
            if block not in ANATOMY and block != namespace and not block.startswith(f"{namespace}-"):
                blocks.add(block)
    return blocks


def structure(project, namespace):
    """Pages with their titles, and each component and page stylesheet with its classes and the pages that use them."""
    pages = {}
    for page in html_pages(project):
        parsed = PageClasses()
        parsed.feed(page.read_text(encoding="utf-8"))
        pages[page.relative_to(project).as_posix()] = parsed
    sheets = []
    for folder in ("components", "pages"):
        for sheet in sorted((project / "css" / folder).glob("*.css")) if (project / "css" / folder).is_dir() else []:
            blocks = sorted(css_blocks(sheet.read_text(encoding="utf-8"), namespace))
            used = [rel for rel, parsed in pages.items()
                    if any(c == b or c.startswith((b + "__", b + "--")) for b in blocks for c in parsed.classes)]
            sheets.append((sheet.relative_to(project).as_posix(), blocks, used))
    return [(rel, " ".join(parsed.title.split())) for rel, parsed in pages.items()], sheets


def listed(describer, paths, added):
    return " · ".join(f"`{p}` {describer.value(p)}" + (" (added)" if p in added else "") for p in paths) or "_None._"


def project_title(project):
    """The README's first heading, or the folder name."""
    readme = project / "README.md"
    if readme.is_file():
        for line in readme.read_text(encoding="utf-8").splitlines():
            if line.startswith("# "):
                return line[2:].strip()
    return project.name


def font_faces(project):
    """The project's @font-face rules, with their font files found from the project folder."""
    faces = []
    for css in sorted((project / "css").rglob("*.css")):
        text = re.sub(r"/\*.*?\*/", "", css.read_text(encoding="utf-8"), flags=re.S)
        for preludes, body in css_rules(text):
            if preludes[-1] != "@font-face":
                continue

            def moved(match):
                url = match.group(2)
                if re.match(r"[a-z][\w+.-]*:|/|#", url):
                    return match.group(0)
                target = (css.parent / url).resolve()
                try:
                    return f'url("{target.relative_to(project.resolve()).as_posix()}")'
                except ValueError:
                    return match.group(0)

            faces.append("@font-face {" + re.sub(r"""url\((["']?)([^"')]+)\1\)""", moved, body) + "}")
    return faces


def gather(project, system, exceptions):
    """Everything DESIGN-SYSTEM.md and DESIGN-SYSTEM.html show, gathered once so the two always agree."""
    tokens = system.tokens
    baseline = collect(json.loads(BASELINE.read_text(encoding="utf-8")))
    config = config_of(project)

    def group(prefix, scale=None):
        found = [p for p in tokens if p.startswith(prefix)]
        return sorted(found, key=lambda p: scale.get(p, 0)) if scale is not None else found

    breakpoints = {}
    for px, name in project_breakpoints(project).items():
        breakpoints.setdefault(name, px)
    namespace = namespace_for(project / "tokens")
    pages, sheets = structure(project, namespace)
    colours = group("color.")
    return SimpleNamespace(
        title=project_title(project), namespace=namespace, system=system, exceptions=exceptions,
        d=Describer(tokens), base=Describer(baseline),
        added=[p for p in tokens if p not in baseline],
        changed=[p for p in tokens if p in baseline and tokens[p]["$value"] != baseline[p]["$value"]],
        source=notes(config.get("source", "")),
        **{key: notes(config.get(key, [])) for key in ("assumptions", "deviations", "normalizations", "readability")},
        roles=[p for p in colours if not p.startswith("color.palette.")],
        palette=[p for p in colours if p.startswith("color.palette.")],
        families=group("font.family."), sizes=group("font.size.", system.font_size),
        weights=group("font.weight.", system.weight), line_heights=group("font.line-height.", system.line_height),
        tracking=group("font.tracking."), text_styles=group("text."),
        spacing=group("space.", system.spacing), radii=group("radius.", system.radius), shadows=group("shadow."),
        button=group("button."), layout=group("layout."),
        breakpoints=sorted(breakpoints.items(), key=lambda item: item[1]),
        pages=pages, sheets=sheets,
        themes=project_themes(project), theme_css=[css for css, _ in theme_rules(project)], font_faces=font_faces(project),
    )


def render(project, system, exceptions):
    """DESIGN-SYSTEM.md."""
    return markdown(gather(project, system, exceptions))


def markdown(g):
    exceptions = g.exceptions
    d, base = g.d, g.base
    out = [HEADER]
    out.append("## Where this design came from\n")
    out.append("Source: " + (" ".join(g.source) if g.source else "_not recorded yet: add \"source\" to portably.config.json._") + "\n")
    out.append("### Assumptions\n")
    out.append("Decisions made where the source was silent or unclear, including values Portably's defaults filled in.\n")
    out.append(bullets(g.assumptions))
    out.append("### Deviations from the source\n")
    out.append("Deliberate differences: substituted fonts, images or icons, simplifications, changes that were asked for. "
               "Colours changed for readability are listed further down.\n")
    out.append(bullets(g.deviations))

    out.append("## What this project decided\n")
    out.append(f"Portably starts every project from a complete default system. This project changed "
               f"{plural(len(g.changed), 'default value')}, added {plural(len(g.added), 'token')}, recorded "
               f"{plural(len(g.normalizations), 'normalization')}, "
               f"{plural(len(g.readability), 'change')} for readability and {plural(len(exceptions), 'exception')}.\n")
    out.append("### Changed from the Portably defaults\n")
    out.append(table(("Token", "Portably default", "This project", "Notes"),
                     [(f"`{p}`", base.shown(p), d.shown(p), d.note(p)) for p in g.changed]))
    out.append("### Added for this project\n")
    out.append(table(("Token", "Value", "Notes"), [(f"`{p}`", d.shown(p), d.note(p)) for p in g.added]))

    out.append("## Pages and components\n")
    out.append("Pages: " + (" · ".join(f"`{rel}`" + (f" ({title})" if title else "") for rel, title in g.pages) or "_None._") + "\n")
    out.append("Each component and page stylesheet, the classes it styles and the pages that use them. "
               "Moving to a framework, each component file becomes a component.\n")
    out.append(table(("Stylesheet", "Classes", "Used on"),
                     [(f"`{rel}`", " ".join(f"`{b}`" for b in blocks) or "_none_",
                       ", ".join(f"`{u}`" for u in used) or "_no page yet_") for rel, blocks, used in g.sheets]))

    out.append("## Colours\n")
    out.append(table(("Role", "Value", "Notes"), [(f"`{p}`", d.shown(p), d.note(p)) for p in g.roles]))
    out.append("Palette: " + listed(d, g.palette, g.added) + "\n")

    out.append("## Typography\n")
    out.append("Fonts: " + (" · ".join(f"`{p}` {d.value(p)}" for p in g.families) or "_None._") + "\n")
    out.append("Sizes: " + listed(d, g.sizes, g.added) + "\n")
    out.append("Weights: " + listed(d, g.weights, g.added) + "\n")
    out.append("Line heights: " + listed(d, g.line_heights, g.added) + "\n")
    out.append(table(("Text style", "Size · weight · line height", "Notes"),
                     [(f"`{p}`", d.value(p), d.note(p)) for p in g.text_styles]))

    out.append("## Spacing\n")
    out.append("Steps (4px grid): " + listed(d, g.spacing, g.added) + "\n")

    out.append("## Radius and shadows\n")
    out.append("Radius: " + listed(d, g.radii, g.added) + "\n")
    out.append(table(("Shadow", "Value"), [(f"`{p}`", d.value(p)) for p in g.shadows]))

    out.append("## Button\n")
    out.append(f"The shape of the Portably button (`{g.namespace}-btn`); its colours come from the action roles.\n")
    out.append(table(("Token", "Value"), [(f"`{p}`", d.shown(p)) for p in g.button]))

    out.append("## Layout and breakpoints\n")
    out.append(table(("Token", "Value", "Notes"), [(f"`{p}`", d.shown(p), d.note(p)) for p in g.layout]))
    out.append("Breakpoints: " + " · ".join(f"{fmt(px)}px ({name})" for name, px in g.breakpoints) + "\n")

    out.append("## Normalizations\n")
    out.append("Values that were almost the same as a token and were snapped to it.\n")
    out.append(bullets(g.normalizations))

    out.append("## Changed for readability\n")
    out.append("Colours from the design that were adjusted so text and controls meet the contrast guideline (WCAG AA).\n")
    out.append(bullets(g.readability))

    out.append("## Exceptions\n")
    out.append("Deliberate one-off values, marked `/* exception: reason */` in the CSS.\n")
    out.append(table(("Where", "Value", "Reason"),
                     [(f"`{e.file}:{e.line}`", f"`{e.snippet}`", e.reason) for e in exceptions]))
    return "\n".join(out)


def write_design_doc(project, system, exceptions):
    """Write DESIGN-SYSTEM.md and DESIGN-SYSTEM.html where their content changed. Return the names written."""
    g = gather(project, system, exceptions)
    written = []
    for name, text in ((FILENAME, markdown(g)), (PAGE_FILENAME, render_page(g))):
        path = project / name
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8")
            written.append(name)
    return written
